# Crea una branch con i font scaricati e apre automaticamente una PR (non push su main)
on:
  workflow_dispatch:

jobs:
  fetch-fonts-and-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # necessario per push su nuova branch e per creare PR con token
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare directories
        run: mkdir -p assets/fonts

      - name: Fetch Google Fonts CSS
        env:
          GOOGLE_FONTS_CSS: "https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700&family=Roboto:wght@400;500&display=swap"
        run: |
          set -euo pipefail
          curl -s -A "Mozilla/5.0 (compatible;)" "$GOOGLE_FONTS_CSS" -o /tmp/gf.css
          echo "Saved /tmp/gf.css (size: $(stat -c%s /tmp/gf.css) bytes)"

      - name: Extract and download font files
        run: |
          set -euo pipefail
          grep -oE "url\([^)]+\)" /tmp/gf.css | sed -E "s/url\((https?:[^)]*)\)/\1/" | sed 's/^"//' | sed "s/^'//" | sed 's/"$//' | sed "s/'$//" | sort -u > /tmp/font-urls.txt || true
          while IFS= read -r url; do
            [ -z "$url" ] && continue
            fname=$(basename "${url%%\?*}")
            if [ ! -f "assets/fonts/$fname" ]; then
              echo "Downloading $url -> assets/fonts/$fname"
              curl -fL "$url" -o "assets/fonts/$fname"
            else
              echo "Already exists: assets/fonts/$fname"
            fi
          done < /tmp/font-urls.txt || true

      - name: Generate fonts.css (local refs + font-display)
        run: python3 scripts/selfhost_fonts.py /tmp/gf.css assets/fonts/fonts.css

      - name: Show generated fonts.css head
        run: sed -n '1,120p' assets/fonts/fonts.css || true

      - name: Create branch, commit and push
        env:
          BRANCH: "fonts/selfhost-$(date +'%Y%m%d-%H%M')"
        run: |
          set -euo pipefail
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git checkout -b "$BRANCH"
          git add assets/fonts || true
          git commit -m "chore: add self-hosted fonts (Montserrat, Roboto)" || echo "no changes to commit"
          git push --set-upstream origin "$BRANCH"

      - name: Create Pull Request
        env:
          PR_TITLE: "chore: add self-hosted fonts (auto PR)"
          PR_BODY: "This PR contains self-hosted font files and assets/fonts/fonts.css generated by GitHub Actions. Review & merge to switch to self-hosted fonts."
        run: |
          # create PR using REST API
          API_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls"
          DATA=$(jq -n --arg t "$PR_TITLE" --arg b "$PR_BODY" --arg head "$BRANCH" --arg base "main" '{title:$t, body:$b, head:$head, base:$base}')
          curl -s -X POST -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github+json" "$API_URL" -d "$DATA" | jq -r '.html_url // .message' || true
